[env:esp32]
platform  = espressif32
board     = nodemcu-32s
framework = espidf

board_build.partitions = partitions_wiimote.csv

build_flags =
    -DCONFIG_BT_ENABLED=1
    -DCONFIG_CLASSIC_BT_ENABLED=1
    -DCONFIG_BT_SPP_ENABLED=0
    -DCONFIG_GATTS_ENABLE=0
    -DCONFIG_GATTC_ENABLE=0
    -DCONFIG_BLE_MESH=0
    -DCONFIG_BT_HID_DEVICE_ENABLED=0
    -DLOG_LOCAL_LEVEL=ESP_LOG_DEBUG

monitor_speed = 115200
monitor_filters = esp32_exception_decoder
